name: CI/CD Workflow

on:
  push:
    branches:
      - main
    paths:
      - 'src/Application/**'
  pull_request:
    branches:
      - main
    paths:
      - 'src/Application/**'

env:
  registryName: d63bpskoxfigimpnpreg.azurecr.io
  repositoryName: techexcel/dotnetcoreapp
  dockerFolderPath: ./src/Application/src/RazorPagesTestSample
  tag: ${{ github.sha }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x'

    - name: Restore dependencies
      run: dotnet restore ./src/Application/src/RazorPagesTestSample/RazorPagesTestSample.csproj

    - name: Build application
      run: dotnet build ./src/Application/src/RazorPagesTestSample/RazorPagesTestSample.csproj --configuration Release --no-restore

    - name: Run tests
      run: dotnet test ./src/Application/tests/RazorPagesTestSample.Tests/RazorPagesTestSample.Tests.csproj --no-build --verbosity normal

  build-docker:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Build Docker image
      run: docker build -t ${{ env.registryName }}/${{ env.repositoryName }}:${{ env.tag }} ${{ env.dockerFolderPath }}

    - name: Login to Azure Container Registry
      uses: azure/docker-login@v1
      with:
        login-server: ${{ secrets.ACR_LOGIN_SERVER }}
        username: ${{ secrets.ACR_USERNAME }}
        password: ${{ secrets.ACR_PASSWORD }}

    - name: Push Docker image to Azure Container Registry
      run: docker push ${{ env.registryName }}/${{ env.repositoryName }}:${{ env.tag }}

# create a new job to deploy webapp
  deploy-to-dev:
  
    runs-on: ubuntu-latest
    needs: build-docker
    environment:
      name: dev
      url: https://d63bpskoxfigi-dev.azurewebsites.net/
    
    steps:
      - name: 'Login via Azure CLI'
        uses: azure/login@v2.1.1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - uses: azure/webapps-deploy@v2
        with:
          app-name: 'd63bpskoxfigi-dev'
          images: ${{ env.registryName }}/techexcel/dotnetcoreapp:${{ env.tag}}

  deploy-to-test:
  
    runs-on: ubuntu-latest
    needs: deploy-to-dev
    environment:
      name: test
      url: https://d63bpskoxfigi-test.azurewebsites.net/
    
    steps:
      - name: 'Login via Azure CLI'
        uses: azure/login@v2.1.1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - uses: azure/webapps-deploy@v2
        with:
          app-name: 'd63bpskoxfigi-test'
          images: ${{ env.registryName }}/techexcel/dotnetcoreapp:${{ env.tag}}

  deploy-to-prod:
  
    runs-on: ubuntu-latest
    needs: deploy-to-test
    environment:
      name: prod
      url: https://d63bpskoxfigi-prod.azurewebsites.net/
    
    steps:
      - name: 'Login via Azure CLI'
        uses: azure/login@v2.1.1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - uses: azure/webapps-deploy@v2
        with:
          app-name: 'd63bpskoxfigi-prod'
          images: ${{ env.registryName }}/techexcel/dotnetcoreapp:${{ env.tag}}
