name: CI/CD Workflow

on:
  push:
    branches:
      - main
    paths:
      - 'src/Application/**'
  pull_request:
    branches:
      - main
    paths:
      - 'src/Application/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x'

    - name: Restore dependencies
      run: dotnet restore ./src/Application/src/RazorPagesTestSample/RazorPagesTestSample.csproj

    - name: Build application
      run: dotnet build ./src/Application/src/RazorPagesTestSample/RazorPagesTestSample.csproj --configuration Release --no-restore

    - name: Run tests
      run: dotnet test ./src/Application/tests/RazorPagesTestSample.Tests/RazorPagesTestSample.Tests.csproj --no-build --verbosity normal

#   build-docker:
#     runs-on: ubuntu-latest

#     steps:
#     - name: Checkout code
#       uses: actions/checkout@v3

#     - name: Build Docker image
#       run: docker build -t razorpages-testsample:latest ./src/Application/src/RazorPagesTestSample

#     - name: Login to Azure Container Registry
#       uses: azure/docker-login@v1
#       with:
#         login-server: ${{ secrets.ACR_LOGIN_SERVER }}
#         username: ${{ secrets.ACR_USERNAME }}
#         password: ${{ secrets.ACR_PASSWORD }}

#     - name: Push Docker image to Azure Container Registry
#       run: docker push ${{ secrets.ACR_LOGIN_SERVER }}/razorpages-testsample:latest